/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul_4;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class Aplikasi_Kelola_Tugas extends javax.swing.JFrame {
        
       String matakuliah;
       String deadlineTugas;
       String detailTugas;
      
       DefaultListModel<String> listTugas = new DefaultListModel<>();
       DefaultListModel<String> listDetail = new DefaultListModel<>();
       
       
    /**
     * Creates new form Aplikasi_Kelola_Tugas
     */
    public Aplikasi_Kelola_Tugas() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.a
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabKelolaTugas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTambahTugas = new javax.swing.JLabel();
        lblNamaMatkul = new javax.swing.JLabel();
        lblDateline = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        txtNamaMatkul = new javax.swing.JTextField();
        txtDeadline = new javax.swing.JTextField();
        bExit = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bRiset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDetail = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblDaftarTugas = new javax.swing.JLabel();
        lblDetailTugas = new javax.swing.JLabel();
        bRiset2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListDaftarTugas = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDetailTugas = new javax.swing.JTextArea();
        bRiset3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabKelolaTugas.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        lblTambahTugas.setBackground(new java.awt.Color(0, 153, 153));
        lblTambahTugas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTambahTugas.setForeground(new java.awt.Color(255, 255, 255));
        lblTambahTugas.setText("Tambah Tugas Baru");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblTambahTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblTambahTugas)
                .addGap(16, 16, 16))
        );

        lblNamaMatkul.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaMatkul.setText("Nama Mata Kuliah      ");

        lblDateline.setForeground(new java.awt.Color(255, 255, 255));
        lblDateline.setText("Deadline Tugas            ");

        lblDetail.setBackground(new java.awt.Color(255, 255, 255));
        lblDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblDetail.setText("Detail                             ");

        txtNamaMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMatkulActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bRiset.setText("Hapus");
        bRiset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRisetActionPerformed(evt);
            }
        });

        taDetail.setColumns(20);
        taDetail.setRows(5);
        jScrollPane2.setViewportView(taDetail);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bRiset)
                        .addGap(18, 18, 18)
                        .addComponent(bSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(bExit))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNamaMatkul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaMatkul)
                            .addComponent(txtDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaMatkul)
                    .addComponent(txtNamaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateline)
                    .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bRiset)
                    .addComponent(bExit))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabKelolaTugas.addTab("Tambah Tugas", jPanel1);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));

        lblDaftarTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDaftarTugas.setText("Daftar Tugas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lblDaftarTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDaftarTugas)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblDetailTugas.setText("Detail Tugas :");

        bRiset2.setBackground(new java.awt.Color(204, 204, 204));
        bRiset2.setText("Hapus semua");
        bRiset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRiset2ActionPerformed(evt);
            }
        });

        ListDaftarTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListDaftarTugasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ListDaftarTugas);

        txtDetailTugas.setColumns(20);
        txtDetailTugas.setRows(5);
        jScrollPane5.setViewportView(txtDetailTugas);

        bRiset3.setBackground(new java.awt.Color(204, 204, 204));
        bRiset3.setText("hapus");
        bRiset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRiset3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetailTugas)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(bRiset3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(bRiset2))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblDetailTugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bRiset3)
                            .addComponent(bRiset2))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabKelolaTugas.addTab("Kelola Tugas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabKelolaTugas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabKelolaTugas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMatkulActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        
        matakuliah = txtNamaMatkul.getText();
        deadlineTugas = txtDeadline.getText();
        detailTugas = taDetail.getText();

        if (matakuliah.isEmpty() && deadlineTugas.isEmpty() && detailTugas.isEmpty() || matakuliah.isEmpty() || deadlineTugas.isEmpty() || detailTugas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai yang valid! dan pastikan terisi semua", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            String tugas = (listTugas.size() + 1) + "." + matakuliah + " ( Deadline : " + deadlineTugas + ")";
            listTugas.addElement(tugas);
            listDetail.addElement(detailTugas);

            // Update model data untuk ListDaftarTugas
            ListDaftarTugas.setModel(listTugas);

            JOptionPane.showMessageDialog(this, "Data Telah diSimpan");

            txtNamaMatkul.setText("");
            txtDeadline.setText("");
            taDetail.setText("");
            
        }
      
        
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bRiset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRiset2ActionPerformed
        
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
        "Anda yakin ingin mereset semua data tugas?", "Konfirmasi Reset", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            listTugas.clear();
            detailTugas = "";
            txtDetailTugas.setText(detailTugas);
        
        }
        
    }//GEN-LAST:event_bRiset2ActionPerformed

    private void bRisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRisetActionPerformed
        
        if (!txtNamaMatkul.getText().isEmpty() || !txtDeadline.getText().isEmpty() || !taDetail.getText().isEmpty()) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Anda yakin ingin mereset semua kolom?", "Konfirmasi Reset", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                txtNamaMatkul.setText("");
                txtDeadline.setText("");
                taDetail.setText("");
            }
        }
                
    }//GEN-LAST:event_bRisetActionPerformed
    
    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
       
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
        "Anda yakin ingin keluar dari aplikasi ini?", "Konfirmasi Keluar", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_bExitActionPerformed

    private void ListDaftarTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListDaftarTugasMouseClicked
        
        if (evt.getClickCount() == 1) {
            int pilihIndex = ListDaftarTugas.locationToIndex(evt.getPoint());
            if (pilihIndex >= 0) {
                
                // Mendapatkan nilai dari nomer yang dipilih
                
                String pilihdetail = listDetail.getElementAt(pilihIndex);
                txtDetailTugas.setText(pilihdetail);
            }
        }
        
    }//GEN-LAST:event_ListDaftarTugasMouseClicked

    private void bRiset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRiset3ActionPerformed
        
        int pilihIndex = ListDaftarTugas.getSelectedIndex();
        
        if (pilihIndex != -1) {
            listTugas.remove(pilihIndex);
            listDetail.removeElementAt(pilihIndex);

            // Menyusun ulang nomor urut di list tugas
            for (int i = pilihIndex; i < listTugas.size(); i++) {
                String tugas = listTugas.getElementAt(i);
                int noUrutBaru = Integer.parseInt(tugas.substring(0, tugas.indexOf("."))) - 1;
                String newTugas = noUrutBaru + tugas.substring(tugas.indexOf("."));
                listTugas.set(i, newTugas);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih tugas yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        txtDetailTugas.setText(""); // Membersihkan area detail setelah menghapus

    }//GEN-LAST:event_bRiset3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kelola_Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kelola_Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kelola_Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kelola_Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi_Kelola_Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListDaftarTugas;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bRiset;
    private javax.swing.JButton bRiset2;
    private javax.swing.JButton bRiset3;
    private javax.swing.JButton bSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDaftarTugas;
    private javax.swing.JLabel lblDateline;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblDetailTugas;
    private javax.swing.JLabel lblNamaMatkul;
    private javax.swing.JLabel lblTambahTugas;
    private javax.swing.JTextArea taDetail;
    private javax.swing.JTabbedPane tabKelolaTugas;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextArea txtDetailTugas;
    private javax.swing.JTextField txtNamaMatkul;
    // End of variables declaration//GEN-END:variables
}
